### PR TITLE
Pattern

### PR DESCRIPTION
**Pull request by avitex**
Finding patterns within input

### CODE REVIEW

**Comment by avitex** [comment]
I know you probably won't be using this fully (this is mostly for SIMD optimisations and change the interface much), but thought I would ping you in this to see what you think @Byron. Your opinion is valued as someone using the library.

The only significant change here for most basic usage is:

- It will be recommended to change `r.take_while(|b| b != b'?')` (looking for a known token) to `r.take_until(b'?')`.
  Internally, if the `simd` feature is enabled, this will perform a vectorized search and if not, will fallback to a naive impl.
- `r.take_while(|b| /*..*/)` now requires the type is explicitly annotated in closures like so: `r.take_while(|b: u8| /*..*/)`.
  Not a significant change, but a change regardless.

This change makes handling delimiters easier too:

```rust
// Instead of having to do this:
r.skip_while(|b| b != b',');
r.consume(b',');

// We can do this (which is also optionally SIMD optimised)
r.take_until_consume(b',')
```

**Comment by avitex** [comment]
Merged in manually

**Comment by Byron** [comment]
Thanks a lot, exactly what I need! I will try it right away by using the git repository for a while!

**Comment by Byron** [comment]
It's interesting, I couldn't actually get it to work, will keep trying though. The signatures surely got more complicated now.

```Rust
#[must_use]
fn skip_whitespace_or_comment<'a, E: From<ExpectedValue<'a>>>(
    r: &mut BytesReader<'a, E>,
    to_where: ConsumeTo,
) -> Option<&'a [u8]> {
    fn skip_whitespace_or_comment<'a, E: From<ExpectedValue<'a>>>(r: &mut BytesReader<'a, E>, to_where: ConsumeTo) {
        fn skip_comment<'a, E: From<ExpectedValue<'a>>>(r: &mut BytesReader<'a, E>) -> usize {
            if r.peek_eq(b'#') {
                r.take_until(|c: u8| c != b'\n').map(|r| r.len()).unwrap_or_default()
            } else {
                0
            }
        }
[…]
```

yields

```

38 |                 r.take_until(|c: u8| c != b'\n').map(|r| r.len()).unwrap_or_default()
   |                   ^^^^^^^^^^ the trait `From<[closure@git-config/src/parse.rs:38:30: 38:48]>` is not implemented for `Value<'_>`
   |
   = help: the following implementations were found:
             <Value<'i> as From<&'i [u8; 0]>>
             <Value<'i> as From<&'i [u8; 1024]>>
             <Value<'i> as From<&'i [u8; 10]>>
             <Value<'i> as From<&'i [u8; 11]>>
           and 33 others
```

Probably it's related to me using `Infallible` while an error type snuck in there now.

**Comment by avitex** [comment]
@Byron Oh for your case you probably would be interested in `take_until_opt` which doesn't require an error :). On a side note I'm still meaning to have a look at your work either tonight or tomorrow. Just wrapping my head around something at the moment.

**Comment by Byron** [comment]
> @Byron Oh for your case you probably would be interested in take_until_opt which doesn't require an error :).

🤦‍♂️ - that works like a charm and I…didn't see it. Thanks for your continued help, it's something I couldn't appreciate more! And of course I am happy to provide more real-life use and mis-use of `dangerous` 😁, that can only help to make it (even) better.

**Pull request closed without merging**
